# Import the urllib.parse module
import urllib.parse as urlparse1

# Sample URL with tokens in the fragment part
url = "https://example.com/#id_token=eyJraWQiOiIxcXk5YmlVaGxwXC9abGZ5NXVYemxyR0x5UGJLWG5MY2s0WmZOMVhlYVJBZz0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoibVBCZGowaUMtQ0pNNWE0UUhwcVFOUSIsInN1YiI6ImIxOTM5ZGRhLWMwMzEtNzA0Ny01YjE5LWUyOWZjZGE3NWJhNCIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGgtMS5hbWF6b25hd3MuY29tXC9hcC1zb3V0aC0xXzNlaHlsQmRPTyIsImNvZ25pdG86dXNlcm5hbWUiOiJ0ZXN0MTIzIiwiYXVkIjoiNG5mNXU5a3R0azk0aTB1cjVxNG0zZmZwYTAiLCJldmVudF9pZCI6IjNmOTMzNDRhLTJkZmUtNDIxYi04MmNjLWQ4MmQzMjM2NWRhOCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzA5MDI1OTQzLCJleHAiOjE3MDkwMjk1NDMsImlhdCI6MTcwOTAyNTk0MywianRpIjoiODhlZmFjMjQtZjEyYS00YTJkLTgyZmEtZGI4MWE5YTIzOTU3IiwiZW1haWwiOiJmZXlpYzg4ODQyQGh1aXprLmNvbSJ9.jjRZd7iLMnejcDzGbWFSQE56bxZ0V7bAXBctqVLypyN3HiFjBslfuAS8mALpVVmUvc689VMacsuReXVxkZTh5SEpTLD7cfv9AnZBw70hdkQrlkUrg8-eXULHgiCCDM_yqbtP2rbCdIq-S0ESRzTDAGWiYAymN6lpyEcaYR-GQCWE55lrWTPAvHLi_Qm6namg3wcjlx6HLdpAADaWEDNaguerL_3FEdniNQg4yyzYXccqB-YSyXrcL-nkgJP014uXU9QROs6WqBcOgD1Y13GJlR9jOrKj2PVy3clUg-TNAPb04qYgSxMemAfAAR8B8jdAFH5zssInh-KlN6vnRN_bQg&access_token=eyJraWQiOiJkTWNzSkk3WVpjV1c4Q011M2RwOHlLRlo3NEFPdjR0R2RtN3dVdTNWSEhJPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJiMTkzOWRkYS1jMDMxLTcwNDctNWIxOS1lMjlmY2RhNzViYTQiLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuYXAtc291dGgtMS5hbWF6b25hd3MuY29tXC9hcC1zb3V0aC0xXzNlaHlsQmRPTyIsInZlcnNpb24iOjIsImNsaWVudF9pZCI6IjRuZjV1OWt0dGs5NGkwdXI1cTRtM2ZmcGEwIiwiZXZlbnRfaWQiOiIzZjkzMzQ0YS0yZGZlLTQyMWItODJjYy1kODJkMzIzNjVkYTgiLCJ0b2tlbl91c2UiOiJhY2Nlc3MiLCJzY29wZSI6InBob25lIG9wZW5pZCBlbWFpbCIsImF1dGhfdGltZSI6MTcwOTAyNTk0MywiZXhwIjoxNzA5MDI5NTQzLCJpYXQiOjE3MDkwMjU5NDMsImp0aSI6ImVjYWZlNjYwLTE2OWEtNGE2YS05ZTAwLTMzZjc1ZTc2NGFmZSIsInVzZXJuYW1lIjoidGVzdDEyMyJ9.DAj0iukkYQPewCaOf73kQpVo3UcnjQRRbUqI3MeQ11TspgAAidgndggT2D6rEw74F9Wh5LLeCT7xkEoaXDfMg05OjYiUImT8_2DtqmFe9LwapfOmPBTQxIwRM1rDdhyZtA8xlrhE9VXvRWCmwgHiseKywuydNNpAU_lmImcVvo0TLn0wCkIPgnmHyyMhgiOLv9UZQTVwrNIsJXV4ReHi3RDj-gkxdedpsCQO4n0xbBZrlO74QGIINJP8kvhjUYvdMf4xzmWfvb-hjzFFTvEfRYNhHVCFx15mKUcy7Ia_gzOGRoXk9Vu79zF1rFU1bAtxheV857nopJyMobNamlaDlA&expires_in=3600&token_type=Bearer"

# Parse the URL
parsed_url = urlparse1.urlparse(url)
# print("parsed - ", parsed_url)
# Extract parameters from the fragment part
fragment_params = urlparse1.parse_qs(parsed_url.fragment)
# print("fragment_params - ", fragment_params)
# Retrieve values for 'id_token' and 'access_token'
id_token = fragment_params.get('id_token', [None])[0]
access_token = fragment_params.get('access_token', [None])[0]

# Print the extracted tokens
print("id_token:", id_token)
print("access_token:", access_token)
