# Import the urllib.parse module
import urllib.parse as urlparse1

# Sample URL with tokens in the fragment part
url = "https://example.com/#id_token=eyJraWQiOiJGOFNid09aeWRsXC92cnM1QXgzS3BiNWFqdHM5cmxaM0VMa0RDUkdjMDRxZz0iLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiVm1tTW1qa2hrQWQyNm9CM0FDc1hEQSIsInN1YiI6IjllNWFiZDU4LTViMTUtNDIxNS1iMGY5LWVkNTlkYWM3OWYxZSIsImNvZ25pdG86Z3JvdXBzIjpbImQ2OGY2NTMwLTQ4NGItNGI5Ni1iOTYwLTliYzVhNzQ2ZDZjMyIsImQ2OGY2NTMwLTQ4NGItNGI5Ni1iOTYwLTliYzVhNzQ2ZDZjMy1BZG1pbiJdLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGV0X3ByZWZlcmVuY2UiOiJkb2dzIiwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmFwLXNvdXRoLTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGgtMV9wZTRFY0IwSEQiLCJjb2duaXRvOnVzZXJuYW1lIjoidGVzdDIzNCIsImF1ZCI6IjQxZTduNnRwdHZrMGdpYmU4Yjk1N3FmcDJhIiwiZXZlbnRfaWQiOiIxNjFlMTliNC1jODQyLTQ1M2QtYmNhZS02NzUwNTQxY2JjMjAiLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTcxMzIwNTkxMSwiZXhwIjoxNzEzMjA5NTExLCJpYXQiOjE3MTMyMDU5MTIsImp0aSI6ImNhZWEwOTZlLWQ2N2UtNDI0OC04MDgwLTY4YTFmNzUyOTYzOSIsImVtYWlsIjoia3VydGphbmUxODA3QGdtYWlsLmNvbSJ9.QD30G1DdW_53LEZtNcltWF_7ux4BPvCPnvJcuJQ832McvMablF8vj74OacYgvQqkdsGq86JQSX_1GFXyc-ISKOHtCFhdT4G5fwmnE8viBaa3JAMJH4yPy7h_TUYokRlLjo7LAydAecIXnUL1fxaqJVPRrp7YTo9tbzOP4hA5MXKVeCerhZb19VTR2WfzXRE8b2ClLFZlDQvJ9Qt4T3mVkT9xq8NmuvHbHUaSVXJ1DLMhyafteSn_BlMjp98LRznBwEWdodhLA-_EbFmHhuGKeJPGzX4URprcekNzUmfEaoQX2oGlx6X0LxZoMvP6PYj-wI3T7MwsrEz2RhgbYryP0Q&access_token=eyJraWQiOiJ2TjlqWDBcL1ViZjVDZlAzazZZRHdwSTJIN0NmRStHS1JVdDhTVENzclk5MD0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI5ZTVhYmQ1OC01YjE1LTQyMTUtYjBmOS1lZDU5ZGFjNzlmMWUiLCJjb2duaXRvOmdyb3VwcyI6WyJkNjhmNjUzMC00ODRiLTRiOTYtYjk2MC05YmM1YTc0NmQ2YzMiLCJkNjhmNjUzMC00ODRiLTRiOTYtYjk2MC05YmM1YTc0NmQ2YzMtQWRtaW4iXSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmFwLXNvdXRoLTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGgtMV9wZTRFY0IwSEQiLCJ2ZXJzaW9uIjoyLCJjbGllbnRfaWQiOiI0MWU3bjZ0cHR2azBnaWJlOGI5NTdxZnAyYSIsImV2ZW50X2lkIjoiMTYxZTE5YjQtYzg0Mi00NTNkLWJjYWUtNjc1MDU0MWNiYzIwIiwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiJwaG9uZSBvcGVuaWQgZW1haWwiLCJhdXRoX3RpbWUiOjE3MTMyMDU5MTEsImV4cCI6MTcxMzIwOTUxMSwiaWF0IjoxNzEzMjA1OTEyLCJqdGkiOiJmMzBhZjljMC1kZmI1LTQxZjQtYWRlZS1kMThmZDIxY2EyNTMiLCJ1c2VybmFtZSI6InRlc3QyMzQifQ.i-zwjXPe0uvygg2D3fhRbi7DJvpWH_XDciDsADT9KV5bMB_RPVvKYd5K8UB6NDk_9u1azsjJXKkMe4N0bCQr12yMNIPr--HsJCvr78gYdst8C8nziqynNkLfLBLZoOr5aD6Vfme6eX_Uvi--8EtFkSGphnEhzgeY75CzzIAP1wRvny3F2BdCEoDYuTnknAf5_KoOZQFhxT7g2kyAERGS8ZnNaG5GebYoDB4i1aqYsk_jZDk5RVclCMR_pMx3le_iD9ltTD1wMR4Lve9ytHcShngT5xlcmlSK0zHHLIUxlwtX967EKuDYVk7shKDppxwz2bqeggyvKRIlN6mixor8YA&expires_in=3600&token_type=Bearer"

# Parse the URL
parsed_url = urlparse1.urlparse(url)
# print("parsed - ", parsed_url)
# Extract parameters from the fragment part
fragment_params = urlparse1.parse_qs(parsed_url.fragment)
# print("fragment_params - ", fragment_params)
# Retrieve values for 'id_token' and 'access_token'
id_token = fragment_params.get('id_token', [None])[0]
access_token = fragment_params.get('access_token', [None])[0]

# Print the extracted tokens
print("id_token:", id_token)
print("access_token:", access_token)
